---
title: Analyzing Lyrics Through the Decades
---

Project done as a part of Stats 133 (UCLA Text Mining Course):

DOWNLOAD [FINAL REPORT](/STATS133_Report.pdf)

### Project Abstract:
It is a well-known fact that culture and identity play a significant role in the development of
musical styles and lyrics (Tran 2023). To test this theory, our team decided to investigate a dataset
containing the top 100 songs from the years 1959-2023 in the USA. Our main goal is to investigate
and analyze the lyrics of every song and discover trends over time, hopefully related to shifts in
our society. To begin, we constructed a corpus from the lyrics column and cleaned the text with
various methods. We decided to split the data into decades, in order to make it easier to see
patterns, differences, and trends. After performing sentiment analysis, looking at most frequency
words and bigrams, using LDA, and even word clouds (all per decade), we then constructed a
predictive model to try and predict whether an artist is male or female based on their lyrics alone.
Our results show how artists react to the ever changing world around them and how words stay
powerful and relevant through all the years.