project:
  type: website

website:
  title: "Lior Levy Meruk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

